### ISSUE TITLE
Option to download docker image

### ISSUE THREAD

**Issue by stefanberndtsson** [bywatersolutions/koha-sandboxes-docker#11]
Most issues can be tested via the web interface, but there are always some that can't. It would be beneficial to have the ability to download a docker image and run it locally. Someone reasonably familiar with docker and Koha on a server could help with sign-off for server side scripts and SIP communication for example.

**Comment by kylemhall** [comment]
I think you should check out https://gitlab.com/koha-community/koha-testing-docker upon which koha-sandboxes-docker is built!

At this time, most of the sandbox system is not itself dockerized, but eventually will be I hope!
